### ISSUE TITLE
[M3/Python] Fatal Error when importing from ROM

### ISSUE THREAD

**Issue by MoriyaFaith** [Artheau/SpriteSomething#119]
Any time a Super Metroid-Based ROM is imported, The same Fatal Error is displayed.
![image](https://user-images.githubusercontent.com/46070717/148667466-6d20ca0a-19c7-4408-869b-b7635d500991.png)
I cannot tell if this is an issue on my end or not, and I can't really put this problem I'm having anywhere else, so I'm putting it here.

**Comment by Artheau** [comment]
Hmm..."file_select" should be caught on line 46 of the same file.  Are you running the pre-compiled binaries or are you running this from source?

**Comment by Artheau** [comment]
Oh, actually I think I see it.  Either Mike or I will check it out soon.
