### ISSUE TITLE
FILENOTFOUNDERROR

### ISSUE THREAD

**Issue by Tow121** [Artheau/SpriteSomething#124]
![image](https://user-images.githubusercontent.com/114936043/193609839-a4e8971a-e85d-4172-8dde-1afae96b8ff8.png)
Brand new SpriteSomething installation and im getting a file not found error because a folder was actually a Cascading Style Sheet Document there for, it couldnt hold the manifest.json thats needed

**Comment by Hithlum** [comment]
It looks like line 61 of source\meta\gui\gamelib.py should be:
`if os.path.isdir(os.path.join(search_path,console)) and not console == "meta" and not console == "js" and not console == "css":`
or anything to prevent it from thinking the js and css folders aren't consoles like the already existing meta check.

**Comment by miketrethewey** [comment]
Should be fixed.
