### ISSUE TITLE
A bit of clarification on how color palette indices are figured out.

### ISSUE THREAD

**Issue by GabrielCNoble** [Artheau/SpriteSomething#153]
Hello, folks. I'd like to ask for a bit of clarification on how SpriteSomething figures out color palette indices and quantizes the input rbg8 to rbg5.

Does it figure out which color palette index each color should occupy before quantizing the color, or does it do it afterwards? I ask this because I'm working on a Super Metroid spritesheet where distinct parts of the power suit have the same color (but not the same palette index), and only some of those same color parts should change when switching to varia or gravity. If the tool figures out palette indices before quantizing, and if it does that by just dropping the 3 lsb of each color component, then I imagine it'd be possible to achieve what i want by just having the color in the parts of the sprite that should not change be 1 greater than those that should change.

Thanks in advance.

**Comment by Artheau** [comment]
This is essentially how I've handled this sort of thing when authoring my own sprite sheets.  You are correct in that you can edit the PNG file with only slightly different rgb8 values and they will be flattened down to the same rgb5 values but still retain the correct color index.  Unfortunately, the reverse is not true, in that if you extract a sprite sheet from the game file, the rgb5 indices do not get uniquely translated into rgb8 values and so this process is not 1-1.  You will want to make sure to use the original PNG sprite sheet when distributing/injecting if your sprite sheet has hidden patterns or details like this.

**Comment by Artheau** [comment]
I will also add the obligatory disclaimer that you should try this on a small sample before you engage on the larger project of authoring the whole sprite sheet under this assumption.  I've done my best to make this tool work as conveniently as possible but there are still a few places where I would do it a little differently if I were to do it again.

**Comment by GabrielCNoble** [comment]
Awesome, thanks for the info :) I'll try this trick with the parts of the sprite sheet I already completed.
