### ISSUE TITLE
Windows only: Animations play half speed while the menu is open

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#16]
The animations slow down to half speed when the user is accessing the File Menu (or any other dropdown menu).  I don't know what causes this.

**Comment by miketrethewey** [comment]
For the record, not an issue in Lubuntu.

**Comment by Artheau** [comment]
Could be just a Windows thing.  This seems related: ["tkInter after() goes slow on Windows"](https://stackoverflow.com/questions/40582797/tkinter-after-goes-slow-on-windows)

**Comment by Artheau** [comment]
I don't think there's anything actionable here.  This seems to be an issue with TkInter and Windows specifically.  If there is no obvious workaround, we should just document this as a known bug and close this issue.
