### ISSUE TITLE
Menu icons for each entry

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#18]
Would be nice aesthetically if icons were consistently present for things where icons made sense.

**Comment by Artheau** [comment]
Is this finished?  We have a lot of icons now.  I don't know if there's any that are good to add that are still missing.

**Comment by miketrethewey** [comment]
I think we're good here since the rest are dynamically included in the Tools menu.

**Comment by miketrethewey** [comment]
Calling it done with 57e62af .
