### ISSUE TITLE
Samus cannon ports

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#20]
Samus needs cannon ports implemented.  Most likely this will be a matter of adding cannon tiles to animations.json and then hooking the spiffy buttons to select for them correctly.

**Comment by miketrethewey** [comment]
Progress starting with dccd870 .

**Comment by miketrethewey** [comment]
As of f124dbc , questions:
Moonwalk: Neutral & Shoot
Crouch Transition: Left Diag Up
Jump: Left Shoot
Spin Jump Launch: Can you aim before spin jumping?
Wall Jump: Does this change with port out?
Fall: Left Shoot
X-Ray: All
X-Ray Crouched: All

**Comment by Artheau** [comment]
As of 118dafa2863ea1ffeb7aa11b460efb87626ac43b

Moonwalk cannon port was very bugged in the vanilla (actually installed backwards!), now updated to reflect the bugfixes packaged in SpriteSomething.
Crouch Transition: fixed
Jump: fixed
Spin Jump Launch: Aiming can be done before spin jumping, but is not technically part of the spin jump launch animation, and so is not yet implemented as a way to "showcase" the spin jump start.
Wall Jump: port is not rendered in-game during this animation
Fall: fixed
X-Ray(both): It is impossible during gameplay to use the x-ray while the cannon port is open, and additionally, there is no data in the ROM on how it should be rendered even if it were possible.

**Comment by Artheau** [comment]
The solution code has been merged into the branch that is addressing Issue #21 via commit 3b6fe54fceac2213964fe86cbd294a1194f24351
