### ISSUE TITLE
Animation-specific palettes

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#23]
- [x] Implement Samus death animation (left/right)
- [x] Animation-Specific Palettes
   - [x] Samus Screw Attack/Spin Attack
   - [x] Samus Shinespark
   - [x] Samus Crystal Flash
   - [x] Samus X-Ray
   - [x] Samus Death
   - [x] Link Zap

**Comment by miketrethewey** [comment]
Fixed Crystal Flash & Samus Death (afaik) in 5930e1f .

**Comment by miketrethewey** [comment]
Fixed Shinespark (afaik) in 8ba2e31 .

**Comment by Artheau** [comment]
Screw attack and spin attack will be included in the changes incorporated by #37

**Comment by Artheau** [comment]
Some of the animations display their palettes correctly, but the timing is off because there are additional frames using other palettes.  This is most noticeable in the death pose for Samus.

**Comment by miketrethewey** [comment]
XRay/Nightvision is #40

**Comment by miketrethewey** [comment]
Need to locate and hard-code Zap palette and have it hooked into something like `zap_mail` or `zap_variant` and then insert it into `animations.json` for `Zap` and `Ether`.

**Comment by miketrethewey** [comment]
Done with e5d442f .

**Comment by miketrethewey** [comment]
Re-opening but removing from 1.0 milestone since that part is fixed.
X-Ray/Nightvision for Samus does not have priority over other effect selections, fix this.

**Comment by miketrethewey** [comment]
Fixed in fbe20ae .
