### ISSUE TITLE
Need a unit testing framework

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#25]
The project has grown somewhat larger than we might have anticipated, and so while there are a number of AssertionErrors throughout the code to try to catch problems, we still end up having to fix recurring bugs.  It makes sense to start making new unit tests every time we fix a bug, and the reliance on AssertionErrors slows down the code if we are testing for our own errors and not the kind of things that the user can influence.

This issue is opened to stub the fact that we need a framework for unit tests.  We can then begin adding new tests once we have a first few examples.

**Comment by Artheau** [comment]
8f3dd49d5f539d01724d9991df144fe29941beaf

Hooked up Travis CI and in theory we can start populating tests.py with tests.  Leaving this issue open until there are at least a few representative tests in the test script.

**Comment by miketrethewey** [comment]
Some Samus tests defined in 97c61b8

**Comment by Artheau** [comment]
The framework is started, now closing issue.
