### ISSUE TITLE
Update version numbers automatically

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#38]
Presently we have to update the version number manually each time.  We should update this number using git commit numbers or similar.

We use the semantic versioning format of MAJOR.MINOR.PATCH and we would like to still be able to manually control the version numbers for MAJOR and MINOR, as these correspond to backwards-incompatible updates and refactor milestones.  PATCH should be updated automatically when we commit.

**Comment by miketrethewey** [comment]
Moved toward this in aae02e9 .
`app_resources/meta/manifests/app_version.txt` should be edited to reflect MAJOR & MINOR versions. The PATCH version will be implemented by Travis.
Somehow gotta hook in the constants script file to read this and get the value and make it available for the various scripts that use it.

**Comment by miketrethewey** [comment]
27fb7c4 adds Linux Distro to the filename in case we wanted to build both Bionic & Xenial. Because Xenial is being tested and built on both Python 3.7 & 3.6, the 3.6 would overwrite the 3.7, provided we ever get the Deployment stuff figured out and a new regex for determining all the files to put up (as referenced in 8f24d57).

**Comment by Artheau** [comment]
We don't need to build for Python 3.6.  The person running the executable doesn't end up knowing which version of Python it was built with.

**Comment by miketrethewey** [comment]
We're still building on Xenial 3.7 & 3.6 but not deploying either of them.
Trusty rotated out in April of 2019.
Xenial will rotate out in April of 2021.
Bionic will rotate out in April of 2023.
Python 3.6.8 final was released Q4 2018.
Python 3.7 final is expected Q3 2020.

Yeah. I suggest we drop 3.6 testing/building but keep Xenial testing/building until it rotates out.
Keep the deployment set as-is (not deploying Xenial at all).

**Comment by Artheau** [comment]
I see value in keeping the tests for 3.6 and Xenial in case someone on those systems wants to build from source, and these run quickly in Travis also.  For builds/deployment, probably need feedback from Linux users on what they would want here.

**Comment by miketrethewey** [comment]
Stable is now testing/building/not deploying Xenial on 3.6 & 3.7 again.
