### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#5]
**Enhancements**
- [x] Click to center sprite
- [ ] Menu icons for each entry
- [x] Customizable overrides for assets and dbs like for custom bgimgs
- [x] Remove Temp assets from SpriteAnimator (assets from ZSpriteTools approved for use)
- [ ] Correct timing issue of animations when menu options are open
- [x] Ferret out P1's export from GIMP error

**Needed**
- [x] Z3 ROM import support
- [x] Z3 ROM export support
- [x] Z3 ZSPR file format support
- [ ] ZSPR metadata tie-ins and "Save as ZSPR"
- [x] VCR Controls
  - [x] Speed up/down (implement)
  - [x] Pose forward/backward (M3, implement)
  - [x] Play 1 (implement)
    - [ ] Current/Total frames per-animation

**Refactoring**
- [x] Refactor timed palette viewing
- [x] Spiffy buttons to imagelib
- [ ] JSON DBs for stuffs
  - [x] Background images per-game
    - [ ] Check against json db and maybe use some magic to calc a title if one not provided 
  - [x] Animation data (M3)
  - [x] Animation data (Z3)
  - [ ] Hook spiffy buttons (M3)
    - [ ] Hook Cannon Port
  - [ ] Hook spiffy buttons (Z3)
    - [ ] Hook Swords
    - [ ] Hook Shields
    - [ ] Include props (weapons, bushes, etc)
  - [x] Specs for inbound game files and variants thereof for smart loading of interface
  - [x] Specs for various ZSPR variants for smart loading of interface
- [x] Iterate over folders: resource v. override

**Comment by Artheau** [comment]
Moved the remaining unfinished tasks over to separate issues.
