### ISSUE TITLE
Populate menu option with available default sprites

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#56]
Iterate over game folders in `app_resources` (all but `meta`), read `app_resources\*\manifests\manifest.json`, grab sprite folders, iterate over sprite folders, make menu option that opens the default sprite file (`<folder_name>.png`) with a proposed hierarchy (likely png, zspr, rdc).
This way the user doesn't need to search for the default sprites.

**Comment by Artheau** [comment]
This task is conceivably made simpler once Samus receives a native format (zspr, rdc), because then we can confine the search to the appropriate type of file.

**Comment by miketrethewey** [comment]
![](https://cdn.discordapp.com/attachments/483880468731789322/616445153758150656/unknown.png)
