### ISSUE TITLE
Index for available custom sprites

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#57]
VT has theirs at: http://alttpr.com/sprites
* GitHub Pages
  * JSON manifest
    * [Samus](http://artheau.github.io/SpriteSomething/app_resources/metroid3/samus/sprites.json)
    * [Link](http://artheau.github.io/SpriteSomething/app_resources/zelda3/link/sprites.json)
  * HTML page
    * [Samus](http://artheau.github.io/SpriteSomething/app_resources/metroid3/samus/sprites.html)
    * [Link](http://artheau.github.io/SpriteSomething/app_resources/zelda3/link/sprites.html)
* GitHub Source
  * [Samus](http://github.com/artheau/spritesomething/blob/gh-pages/app_resources/metroid3/samus/sprites.json)
  * [Link](http://github.com/artheau/spritesomething/blob/gh-pages/app_resources/zelda3/link/sprites.json)

**Comment by Artheau** [comment]
Mike has been making good progress on this.  I like that this is going in a direction that will provide a way to index "tested" sprites that have not yet been made "VT official" or similar.

**Comment by miketrethewey** [comment]
Fixed by 54d5b04 .
