### ISSUE TITLE
Check for Updates

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#58]
Have Travis post to `gh-pages` with an update to the `appversion.txt` or whatever I called it so that it can be available for the app to check against to see if there's a new release.
Options:
- [x] 1: Just check for minor versions (ignore new build versions), just check the latest tag version on the project
- [x] 2: Check for build versions (read posted `appversion.txt` or whatever I called it that gets updated by Travis for each build)

**Comment by Artheau** [comment]
Dinked with gh-pages to make it work using the main repo instead of the fork.

**Comment by miketrethewey** [comment]
Now that it’s using the main repo, I can experiment with Travis integration to the pages interface.
