### ISSUE TITLE
Have CLI output JSON bytecode files

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#59]
Give an output option to give a bytecode file in JSON format instead of writing to a file to promote being able to do server-side patches with the app.

**Comment by Artheau** [comment]
Also, many of the edits in SpriteSomething are of the form:

if old code = 
then new code = 

Maybe some of the non-sprite specific changes should be ported to ASM files?  Devs love ASM files.

**Comment by miketrethewey** [comment]
`move-everything` has stuff in `/source/snes/romhandler.py:350`

**Comment by miketrethewey** [comment]
Merged as of d012405 .
