### ISSUE TITLE
VCR buttons covered up by image descriptions

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#60]
If Samus is loaded, and a new Samus sprite is loaded afterwards, then the VCR buttons are covered up by the image descriptions (e.g. "Play")

**Comment by miketrethewey** [comment]
The panels don’t retain their height. They’re still there and can be stretched to reveal them. Might be able to be remedied with explicit height declarations of the panels.

**Comment by Artheau** [comment]
Fixed by 225fca8cb7d9f291c611309939c11c87ccf0c462
