### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#7]
Prior to refactor
- [x] File
  - [x] Open: Open any file type (PNG, ZSPR, etc.)
  - [x] Save As...: Save any file type (PNG, ZSPR, etc.)
  - [x] Exit: Exit, ask to save if changes made
- [x] Import
  - [x] Inject Into Game File
  - [x] Copy to New Game File
  - [x] Inject into Directory of Game Files
  - [x] Frame as PNG
  - [ ] Animation as GIF
  - [x] Animation as Horizontal Collage
  - [ ] Animation as Vertical Collage?
- [x] Tools
  - [ ] Palette Editor (not in v1.0)
  - [x] Plugins
    - [ ] Sheet Trawler (Z3)
    - [ ] Pose as Tracker Images (Z3)
- [x] Help
  - [x] Diagnostics
  - [x] About

**Comment by Artheau** [comment]
Superceded by [Issue #5](https://github.com/Artheau/SpriteSomething/issues/5)

**Comment by Artheau** [comment]
Bringing this back to re-open the discussion of how best to arrange the menu options.  Ideally, I would push for something that is very minimal, but ultimately there needs to be a balance between minimal presentation and needed functionality.

**Comment by Artheau** [comment]
For v1.0, still need GIF export.

Could also implement some kind of "vertical collage" by iteratively calling horizontal collage and gluing the images together, although the name "sprite sheet" is probably a better description at that point (and the image will be huge).

**Comment by miketrethewey** [comment]
Sheet Trawler is waiting for figuring out how to paint the full sheet and make each cell clickable and then load all the animations with that cell, facilitated by some kind of reverse lookup.
Pose as Tracker Images is waiting for a way to call a specific pose from an animation sequence, with properties like mail color selection, on-demand, and then export as `.png`.

**Comment by Artheau** [comment]
While it comforts me to have this issue remain open in order to remind us to rally around a minimalistic interface, it may be that the only functional purpose of this issue is to remind us of features that we want to implement, which should probably be separated into their own issues at this point.

**Comment by miketrethewey** [comment]
Did the thing as instructed in last comment via issue #68 .
