### ISSUE TITLE
Can't open any sprites

### ISSUE THREAD

**Issue by esanscoopsers** [Artheau/SpriteSomething#90]
I might just be dumb, but I cant get this thing to open any sprites. I've tried exporting a sprite frame then opening it but errors happen. I'm trying to edit samus' sprites in super metroid. I have some already in a rom and working. i can open that rom but I don't know where to go from there. Maybe someone could point me to a tutorial?

**Comment by Artheau** [comment]
Do we still have Nintoaster's Youtube tutorial link?  That would probably be useful here.

**Comment by Artheau** [comment]
I think I found it: https://www.youtube.com/watch?v=2XXrinJpXVc

**Comment by miketrethewey** [comment]
@esanscoopsers Are you still having difficulty?

**Comment by esanscoopsers** [comment]
No issues anymore, thanks for the help.
